### ISSUE TITLE
2_2

### ISSUE THREAD

**Issue by andrey4287252** [IrinaMandarina/Programmistika#2]
Вроде в условии просили воспользоваться списками/кортежами...

**Comment by IrinaMandarina** [comment]
Хорошо, попробую. Файл тогда просто изменю, так?

**Comment by andrey4287252** [comment]
Ага, просто коммит сделать в котором будут изменены файлы-- С уважением, Григорьев Андрей30.09.2020, 11:50, "IrinaMandarina" <notifications@github.com>:
Хорошо, попробую. Файл тогда просто изменю, так?
